module.exports = [
  {
    title: "Blog App",
    description: "First app with backend & frontend",
    url: "https://salty-plains-35347.herokuapp.com/",
    imagePath: "./images/BlogApp.PNG",
    category: "Full Stack",
    id: "blog_app",
    longDescription:
      "My first app connected to an online database. It allows to create posts with text and images. It implements user authentication and authorization, as well as basic security",
    motivation:
      "I was coursing the back-end lessons of The Complete 2021 Web Development Bootcamp, which among other things taught me about REST apps. At the same time I was also doing a course on Bootstrap (Bootstrap 4 From Scratch With 5 Projects), and I came across a Bootstrap exercise with 3 very clear resources (posts, users & categories) and various CRUD operations for them. It felt like adding the logic to that Bootstrap exercise (it had only the front-end) would make a perfect way to practice REST apps.",
    techs: [
      "HTML",
      "CSS",
      "JavaScript",
      "Jquery",
      "Node.js",
      "Express",
      "Ejs templating",
      "MongoDB",
    ],
    tags: [
      "C.R.U.D. (Create, Read, Update and Remove options)",
      "Authentication",
      "Authorizations",
      "Security",
    ],
    repoUrl: "https://github.com/mrtbsc/blog-app",
  },
  {
    title: "Artists CVs App",
    description: "First Backend App",
    url: "https://mighty-river-52981.herokuapp.com/artists",
    imagePath: "./images/ArtistsCVs.PNG",
    category: "Back End",
    id: "first_app",
    longDescription: `It is a basic CRUD app that displays a team of artists. The artists are the resources, which can be added, read, updated and deleted.`,
    motivation:
      "This is the first backend-app I built. To keep it as simple as an express app could get, no database was associated and only minimal CSS was used.",
    techs: ["HTML", "CSS", "Node.js", "Express", "Ejs templating"],
    tags: ["C.R.U.D. (Create, Read, Update and Remove options)"],
    repoUrl: "https://github.com/mrtbsc/first-express-app",
  },
  {
    title: "Bootstrap Multipage",
    description: "First multipage site built with Bootstrap",
    url: "https://mrtbsc.github.io/Projects/Bootstrap-MultiPage/",
    imagePath: "./images/MultiPage.PNG",
    category: "Front End",
    id: "bootstrap_multipage",
    techs: ["HTML", "CSS", "Bootstrap"],
    tags: ["User input", "Navigation", "Background Effects", "Video Players"],
    longDescription: `It is a Bootstrap website that simulates a commercial brand website. It has 5 common pages: home, about, services, blog & contact.`,
    motivation: `It is an exercise project of a course I took on Bootstrap (<a href="https://www.udemy.com/course/bootstrap-4-from-scratch-with-5-projects/">Bootstrap 4 From Scratch With 5 Projects</a>)`,
  },
  {
    title: "Yummy Lunch Form - w/ bootstrap",
    description: "Static bootstrap page with a form",
    url: "https://mrtbsc.github.io/Projects/form-bootstrap/",
    imagePath: "./images/YummyLunchB.PNG",
    category: "Front End",
    id: "bootstrap_form",
    techs: ["HTML", "CSS", "Bootstrap"],
    tags: ["User input"],
    longDescription: `It implements a survey to choose the menu of an imaginary lunch. This is a bootstrap version of a project I first implemented only with HTML & CSS.`,
    motivation: `As I learnt Bootstrap I got interested in remaking old vanilla projects with this famework. This way I was able to get a close comparison between working vanilla versus using a framework.`,
  },
  {
    title: "Sign-up page",
    description: "First page built with Bootstrap",
    url: "https://mrtbsc.github.io/Projects/Bootstrap-SignUp/",
    imagePath: "./images/SignUp.PNG",
    category: "Front End",
    id: "bootstrap_first",
    techs: ["HTML", "CSS", "Bootstrap"],
    tags: ["User input", "Navigation"],
    longDescription: `It is a basic bootstrap page to get started on the framework. It mimics a sign-up page for a techish service.`,
    motivation: `It is an exercise project of a course I took on Bootstrap (<a href="https://www.udemy.com/course/bootstrap-4-from-scratch-with-5-projects/">Bootstrap 4 From Scratch With 5 Projects</a>)`,
  },
  {
    title: "Yummy Lunch Form - css only",
    description: "Static page with a form",
    url: "https://mrtbsc.github.io/Projects/form/",
    imagePath: "./images/YummyLunch.PNG",
    category: "Front End",
    id: "form",
    longDescription: `Its ojective was to practice HTML and CSS forms creating a survey to choose the menu for an imaginary lunch. It also implements responsiveness.`,
    motivation: `The idea came from the very helpful page <a href="https://www.geeksforgeeks.org/top-10-projects-for-beginners-to-practice-html-and-css-skills/">https://www.geeksforgeeks.org/top-10-projects-for-beginners-to-practice-html-and-css-skills/</a> and a rather gluttonous mood.`,
    tags: ["User input"],
    techs: ["HTML", "CSS"],
  },
  {
    title: "City Parallax",
    description: "Static page with the Parallax background effect",
    url: "https://mrtbsc.github.io/Projects/parallax-effect/",
    imagePath: "./images/CityParallax.PNG",
    category: "Front End",
    id: "parallax",
    longDescription:
      "Its ojective was to practice the parallax effect, which is the behaviour of its background images. It uses HTML and CSS and implements responsiveness.",
    motivation: `The idea came from the very helpful page <a href="https://www.geeksforgeeks.org/top-10-projects-for-beginners-to-practice-html-and-css-skills/">https://www.geeksforgeeks.org/top-10-projects-for-beginners-to-practice-html-and-css-skills/</a>`,
    techs: ["HTML", "CSS"],
    tags: ["Background Effects", "Responsive Design"],
  },
  {
    title: "Photo Gallery Page",
    description: "First Static Page",
    url: "https://mrtbsc.github.io/Projects/gallery/",
    imagePath: "./images/Gallery.PNG",
    category: "Front End",
    id: "gallery",
    longDescription:
      " Its ojective was to practice HTML and CSS creating a responsive gallery webpage for an imaginary photography brand.",
    motivation: `The idea to do a Photo gallery and its design came from the very helpful page <a href="https://www.geeksforgeeks.org/top-10-projects-for-beginners-to-practice-html-and-css-skills/">https://www.geeksforgeeks.org/top-10-projects-for-beginners-to-practice-html-and-css-skills/</a>. Since the Photo gallery project there was used more to determine what to create rather than how to code it, there might be several difference in the code between the 2 projects.`,
    tags: [],
    techs: ["HTML", "CSS"],
  },
];
